[tool.poetry]
name = "webrtc-service-transformers-stt-whisper"
version = "0.1.0"
description = ""
authors = ["Vincent Bailleau <vincent.bailleau@al-enterprise.com>"]
readme = "README.md"
packages = [{include = "mgw_svc_stt_whisper", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.10"
openai = "^1.57.3"
webrtc-service-transformers-core = {path = "../webrtc_service_transformers_core"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
