[tool.poetry]
name = "webrtc-service-transformers-cova"
version = "0.1.0"
description = ""
authors = ["Gaël De Chalendar <gael.de-chalendar@cea.fr>"]
readme = "README.md"
packages = [{include = "mgw_svc_cova", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.10"
aiohttp = "^3.11.9"
webrtc-service-transformers-core = { path = "../webrtc_service_transformers_core" }
webrtc-service-transformers-stt-linto = {path = "../webrtc_service_transformers_stt_linto"}
webrtc-service-transformers-stt-whisper = {path = "../webrtc_service_transformers_stt_whisper"}
webrtc-service-transformers-stt-whisper-live = {path = "../webrtc_service_transformers_stt_whisper_live"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
