[tool.poetry]
name = "webrtc-service-transformers-stt-whisper-live"
version = "0.1.0"
description = ""
authors = ["Vincent Bailleau <vincent.bailleau@al-enterprise.com>"]
readme = "README.md"
packages = [{include = "mgw_svc_stt_whisper_live", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.10"
webrtc-service-transformers-core = {path = "../webrtc_service_transformers_core"}
websocket-client = "^1.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
